drop table grade;

CREATE TABLE GRADE(
	LOWSCORE	NUMBER(2),
	HISCORE		NUMBER(3),
	GRADE		VARCHAR2(2)
		CONSTRAINT GRADE_GRADE_PK PRIMARY KEY
);

INSERT INTO GRADE
VALUES(0, 59, 'F');

INSERT INTO GRADE
VALUES(60, 64, 'D0');

INSERT INTO GRADE
VALUES(65, 69, 'D+');

INSERT INTO GRADE
VALUES(70, 74, 'C0');

INSERT INTO GRADE
VALUES(75, 79, 'C+');

INSERT INTO GRADE
VALUES(80, 84, 'B0');

INSERT INTO GRADE
VALUES(85, 89, 'B+');

INSERT INTO GRADE
VALUES(90, 94, 'A0');

INSERT INTO GRADE
VALUES(95, 100, 'A+');

select * from grade;
